### ISSUE TITLE
naming OAuth scopes

### ISSUE THREAD

**Issue by elf-pavlik** [w3c/Micropub#11]
I find name **post** for the OAuth scope extremely confusing.

> For example, most Micropub servers require clients to obtain the "post" scope in order to create posts. - http://indiewebcamp.com/micropub#Scope

'obtain the "post" scope in order to **create posts**'

Does it relate to
1. _create_ from CRUD
2. type of a resource: a posting
3. HTTP POST, which in micropub include update and delete

Proposed by @dissolve _edit_, _delete_ IMO suggest _post_ == _create_ (CRUD), similar mentioned in a spec _post:video_. Please notice recent removal of _Post_ activity type from AS2.0 draft https://github.com/jasnell/w3c-socialwg-activitystreams/pull/122 as well as my similar issue raised in https://github.com/jasnell/w3c-socialwg-activitystreams/issues/88

In case above I would like to propose using well established **CRUD** terminology: _create_, _read_, _update_, _delete_ possibly also _write_ == _create_  + _update_ + _delete_
- http://indiewebcamp.com/scope

For example remoteStorage draft tries to define scopes as <resource type>:r for HTTP GET and HEAD (read) or <resource type>:rw for all HTTP verbs (write). I also allows use of '*' for any resource type.
http://tools.ietf.org/html/draft-dejong-remotestorage-04#section-9

Web Access Control, used in SoLiD, makes distinction between: _Read_, _Write_, _Append_, _Control_
https://www.w3.org/wiki/WebAccessControl#Modes_of_Access

The _Control_ one reminds me of _admin:_\* used by github.

Possibly we could find some common pattern with _mode(:resource_type)_?

@fkooman @skddc @michielbdejong @silverbucket @melvincarvalho

**Comment by elf-pavlik** [comment]
How about using URIs from AS2.0 Vocabulary for scope names of CRUD operations?
- http://www.w3.org/ns/activitystreams#Create
- http://www.w3.org/ns/activitystreams#Read
- http://www.w3.org/ns/activitystreams#Update
- http://www.w3.org/ns/activitystreams#Delete

@jasnell @oshepherd

If we need notion of resource types, we could just authorize access to different collections having distinct URIs (OAuth audience parameter?) e.g microblog, calendar, map, taskboard

**Comment by raucao** [comment]
Not sure what that could look like for RS.

**Comment by aaronpk** [comment]
I'm okay with using the terms "create read update delete" instead of "post". I'm not going to switch to full URIs.

**Comment by dissolve** [comment]
The other sugesting was to limit to categories, sort of like android permissions model. "contacts", "profile", "posts", etc.

**Comment by raucao** [comment]
> The other sugesting was to limit to categories, sort of like android permissions model. "contacts", "profile", "posts", etc.

That's impossible for remoteStorage at least.

**Comment by aaronpk** [comment]
Yes, I fully expect some Micropub APIs to support category-based scope. This is also one of the reasons I am planning on making the scope list customizable during the authorization grant on indieauth.com. https://github.com/aaronpk/IndieAuth.com/issues/72

**Comment by elf-pavlik** [comment]
Earlier today I thought about ways to combine unambiguous mode (CRUD+) with unambiguous category. Maybe using just a Claims Set part of [Unsecured JWTs](https://tools.ietf.org/html/rfc7519#section-6) could come helpful. Assuming `as:` prefix for `http://www.w3.org/ns/activitystreams#` and JSON-LD `@type` keyword (rdf:type)

``` json
{
  "@type": "as:Event",
  "as:verb": "as:Create"
}
```

becomes _scope token_ `eyJAdHlwZSI6ImFzOkV2ZW50IiwiYXM6dmVyYiI6ImFzOkNyZWF0ZSJ9`

something maybe more familiar to IndieWeb community:

``` json
{
  "h": "event",
  "action": "create"
}
```

becomes _scope token_ `eyJoIjoiZXZlbnQiLCJhY3Rpb24iOiJjcmVhdGUifQ`

http://jwt.io

While `create:event` in many ways looks simpler, using standard way of decoding JSON(-LD) could provide more powerful way of defining scopes. Feel free to consider this comment _thinking out loud_

**Comment by elf-pavlik** [comment]
I think action part of micropub scope (action:category), should at least match _mp-action_ parameter, which also includes _undelete_, also maybe _syndicate_ looks like a special case.
BTW I already suggested reusing AS2.0 terms in #4 also with simple verb registry (e.g. https://w3id.org/verb ) we could take convention that part before optional :<category> maps to such commonly defined verbs. Since it may include more verbs than CRUD (admin, syndicate, ?) possibly also worth coordinating common verb definitions with:
- https://www.w3.org/wiki/WebAccessControl#Modes_of_Access
- http://indiewebcamp.com/web-actions#action_do_verbs
- http://microformats.org/wiki/h-listing (p-action)
- http://www.w3.org/TR/activitystreams-vocabulary/#activity-types
- http://schema.org/docs/full.html#Action
- https://developer.github.com/v3/activity/events/types/
- ?

Or at least try not to use post, publish, create, add, new, update, edit, ზმნა, Глагол, צייטווארט etc. at random See also: https://github.com/w3c-social/social-vocab/issues/12

**Comment by aaronpk** [comment]
Elf, I appreciate the thoughts on this, but I don't think it's useful to try to make something up for this until there is more implementation experience. 

I also suspect that individual Micropub endpoints are going to want to treat scope slightly differently on their own. Luckily clients and servers don't actually have to agree on scope. What I mean by that is I can make up my own list of scopes for my micropub endpoint at whatever granularity I want, and as long as _my_ authorization server lets me adjust the scopes I'm granting to a client, the client doesn't care what scopes are ultimately granted and it will still work.

I think leaving scope out of the core spec is a good idea as it allows servers to experiment with it after there are more implementations.

**Comment by dissolve** [comment]
aaronpk.  I would disagree, and don't close this so quickly.

Look at my MP client, ben.thatmustbe.me/new
I am forced to not adjust for what scopes the user has actually allowed.   I request scopes 'post', 'edit', and 'undelete'.  and I would like to say that if they don't allow 'edit' or 'undelete' I can hide those features in the UI or I risk my client not working with any other endpoint.  Because they might be using 'create' to cover all of those or 'manageposts' or something else, my UI cannot adjust to a list of permissions that could be anything.

I would say this is something that should be in the spec.

**Comment by aaronpk** [comment]
I realize there are benefits when the client and server agree on scope values, but I think there is value to allowing further experimentation with scope values by servers. I would rather define a very small set of known scope values in the core spec, and see what happens once there are more implementations.

**Comment by ghost** [comment]
https://tools.ietf.org/html/rfc6750#section-3

This also allows the `WWW-Authenticate` header to indicate which scopes are required for a particular action, e.g. if you try to create a new post on the MP endpoint it could return this header:

```
POST /micropub/
Content-Type: application/x-www-form-urlencoded

h=entry&content=fooooobaaarbazzz
```

```
HTTP/1.1 403 Forbidden
...
WWW-Authenticate: Bearer realm="mp", scope="fancypostscopevalueoftheday"
```

After that you re-request authorization with that particular scope added.

Of course it would be neat if we could just come up with a list of standard scopes, but is also fair to take some more time to figure out what is a good idea for scope and what not. JWT is definitely a bad idea, URLs maybe not so bad... If Google does it... :)

**Comment by elf-pavlik** [comment]
Let's forget JWT. URLs have very cool feature that they allow you to get more information about resource by simple HTTP GET. So for example common scopes can have Human Readable = multiple languages labels https://github.com/w3c-social/social-arch/issues/7

Showing strings in english language may work for small group of geeks but will not satisfy need of 'general population'. I would really like to hear about other possible ways of providing human readable = multilingual labels for scope tokens which app can display in UI.

seeAlso: http://www.w3.org/TR/activitystreams-vocabulary/#dfn-displayname

**Comment by dissolve** [comment]
@aaronpk. That's more what I'm talking about, a small set.   But we still need to define that set.

**Comment by aaronpk** [comment]
Rather than make something up from scratch, the first step is to document existing behaviors. Let's document existing behaviors from sites that currently support scope so we have a better place to draw from. There is already a wiki page for collecting examples, so let's use that. http://indiewebcamp.com/scope

**Comment by elf-pavlik** [comment]
:+1: just [added Google+](https://indiewebcamp.com/scope#Google.2B)

**Comment by ghost** [comment]
Another approach: the MP (Micropub) endpoints choose their AS (authorization server) and have to register with them to 'introspect' the Bearer token from the Micropub client. With the registration at the AS instead of only obtaining a token to be able to verify Bearer tokens also a list of scopes supported by the MP endpoint could be registered that could, in addition to the scopes requested by the MP client be shown to the user at authorization time. 

```
Quill (https://quill.p3k.io/) wants your permission to access your Micropub 
endpoint (https://tuxed.net/micropub/): 

Please review the permissions you want to give to Quill:

Requested by Quill:
[x] post

Supported by your Micropub endpoint:
[x] Create (https://micropub.net/scope#create)
[x] Read (https://micropub.net/scope#read)
[ ] Update (https://micropub.net/scope#update)
[ ] Delete (https://micropub.net/scope#delete)

Please select the permissions you want to give. We will lie to Quill and tell 
them you authorized the 'post' scope.

[ Continue ] [ Reject ]
```

**Comment by aaronpk** [comment]
This is exactly the kind of experimentation I want to see :-) 

We know that the user chooses their authorization server as well as the micropub endpoint, so it's entirely reasonable to assume the two can coordinate on this. I would love to see this implemented!
