### ISSUE TITLE
"url" parameter conflict

### ISSUE THREAD

**Issue by aaronpk** [w3c/Micropub#12]
Using the parameter `url` to indicate the post being edited is problematic, since it prevents modifying a property on the post called `url`. This is not a problem for normal "entry" posts, since the URL will always be generated by the micropub endpoint. However, other content such as contacts, venues or events will have a URL on the website as well as a URL property that indicates the canonical URL or other URLs of the object.

Example: editing a contact on my site, to add an alternate URL to their profile.

```
curl http://example.com/micropub
  -d mp-action=edit
  -d url=http://aaronparecki.com/tantek   # This is the URL of my copy of the contact
  -d url[]=https://twitter.com/t   # this is the URL I want to add to the contact
```

Obviously this request doesn't make sense. I need an alternate parameter name to use to select the contact being edited.

Suggestions:
- `mp-url` - following the convention of using `mp-*` as reserved Micropub parameters
- `id` - implies a unique identifier, and is also the parameter used by ActivityStreams

**Comment by aaronpk** [comment]
Along the lines of #13, another option could be to spell out "micropub" and make the parameters:

```
curl http://example.com/micropub
  -d micropub-action=edit
  -d micropub-id=http://aaronparecki.com/tantek   # This is the URL of my copy of the contact
  -d url[]=https://twitter.com/t   # this is the URL I want to add to the contact
```

**Comment by aaronpk** [comment]
`uid` is not an option either. According to http://microformats.org/wiki/h-entry, `uid` is the universally unique identifier, which means it will always be the external URL, not the URL of the version on my site that is being edited.

**Comment by voxpelli** [comment]
I like the `mp-url` one

**Comment by karadaisy** [comment]
Note url vs. mp-url was discussed on the wiki too. @dissolve was -1 at the time:

https://indiewebcamp.com/Micropub-brainstorming#Explicit_CRUD

**Comment by dissolve** [comment]
@aaronpk I'm not sure mp-uid implies universally, thats why people started using UUID, simply unique to the system.  
Either way, I think mp-id makes a fair bit of sense, gives the freedom to use non-urls as your ID if you so choose.

**Comment by aaronpk** [comment]
The "universal" aspect of uid came from the microformats wiki on [h-entry](http://microformats.org/wiki/h-entry):

```
u-uid - universally unique identifier, typically canonical entry URL
```

At this point it looks like the options are:
- `mp-url`
- `mp-id`

I'm leaning against the `mp-id` option since the implication is that one would have to publish the ID in the page in order for a micropub client to find it, which nobody does yet. The URL of the page is the simpler identifier for it.

**Comment by dissolve** [comment]
Ironically any url for an id implies its universally unique (except subdomain stuff I suppose) 

One way to justify mp-uid is actually that it is the UID of the thing you are editing.  It may not be the canonical copy. 

url (url attached to the entry)
uid (uid of the canonical copy)
mp-url (url of the copy you are editing)
mp-uid (uid of the copy you are editing)  (which for our case actually makes sense to be the mp-url)

My concern of mp-url is that allowing non-url options might be better for micropub  to get used on systems that don't always have a published URL for the item you are editing.  Any system based on usernames, accounts, etc could use it without requiring URL of the item.

**Comment by aaronpk** [comment]
If I post a copy of an h-event from indiewebcamp.com on my site, the uid of that should still be the indiewebcamp.com URL. That's the goal of the "universal" language on the definition of uid. That's why "uid" doesn't make sense to refer to the local ID of the object.

**Comment by voxpelli** [comment]
The `mp-url` doesn't have to be publicly accessible – so any value that's represented in a URL format can be used, even if that URL is for eg. a temporary unpublished draft. Any ID or such can be wrapped up in a URL-structure.

**Comment by dissolve** [comment]
@aaronpk, i'm saying there is a UID to the original post and a UID to a syndicated copy.  the syndicated copy DISPLAYS the UID of the original, but it HAS a UID either way (its syndicated location URL)

I think @voxpelli makes a good case though, the URL can be some internal thing, which does handle my concern.  I suppose I am ok with mp-url.

**Comment by karadaisy** [comment]
> If I post a copy of an h-event from indiewebcamp.com on my site, the uid of that should still be the indiewebcamp.com URL

That doesn't sound right to me at all. My understanding is that that would be equivalent to setting `rel=canonical` on your event page that points to the indiewebcamp.com page. Is that really what you want?

**Comment by aaronpk** [comment]
Yes, I thought that's the idea of having a copy of an object on my site.

**Comment by aaronpk** [comment]
The new format for adding and updating properties no longer conflicts with this parameter, so I am closing the issue since it's not relevant anymore.
