### ISSUE TITLE
Consider eliminating add and update 

### ISSUE THREAD

**Issue by dshanske** [w3c/Micropub#14]
According to the spec as I am reading it, edit is any sort of edit, and below this is update or add. Why can't edit or add as the mp-action dictate the two differing behaviors rather than going down another level?

The behaviors seem to be replace all vs replace only those that don't currently exist.

**Comment by aaronpk** [comment]
The idea of the single "edit" is based on the idea of an "[edit post](http://indiewebcamp.com/edit#Edit_a_specific_property)", which is similar to a Github pull request. A pull request contains many changes, including replacing, adding and deleting content. 

Maybe "replace" would be more clear of a term than "update"?

**Comment by voxpelli** [comment]
Replace is in line with http://jsonpatch.com/

**Comment by aaronpk** [comment]
Yeah I like that, it's way more explicit.

**Comment by aaronpk** [comment]
The new draft uses "replace".
