### ISSUE TITLE
Register link relation with IANA

### ISSUE THREAD

**Issue by dret** [w3c/Micropub#19]
can we do the same here that we did over at https://github.com/w3c/preload/issues/41? if that's ok, i'll happily create a PR for that.

**Comment by aaronpk** [comment]
Sure thing! Thanks for taking the lead on writing it up.

**Comment by dret** [comment]
ok, i'll create a PR in the next couple of days. thanks!

**Comment by dret** [comment]
maybe the description could be improved. but i was struggling to find text that would be appropriate. searching for inspiration in the spec, it occurred to me that such an explanation is missing from the spec as a whole. i opened #21 as a separate issue for this.

**Comment by dret** [comment]
currently, the micropub link relation is not really introduced or defined, it simply appears in the discovery section. from the spec writing point of view, it would be better to more formally introduce it as something that's defined by this spec.

**Comment by dret** [comment]
thanks!
