### ISSUE TITLE
coupling with microformats

### ISSUE THREAD

**Issue by elf-pavlik** [w3c/Micropub#2]
http://indiewebcamp.com/micropub#Reserved_properties

> h - used to specify the object type being created

Using _h_ for type comes intuitive only when assuming use of microformats vocabulary. Specifying _type_ and _url_ properties instead sounds much more generic.

http://indiewebcamp.com/micropub#Creating_Objects

This section clearly assumes use of microformats schema/vocab. How people can use Micropub with ActivityStreams2.0, Schema.org or any other vocabulary/schema aggregated in http://lov.okfn.org/dataset/lov/ ?

**Comment by aaronpk** [comment]
I had never considered using Micropub with anything except the Microformats vocabulary. I suppose it would be an interesting experiment to try to create an AS2.0 object in this style. Ultimately Micropub is intended to be simple POST requests, so a POST request that creates an AS2.0 object shouldn't look too unusual.

**Comment by elf-pavlik** [comment]
http://socialwg.indiewebcamp.com/irc/social/2015-05-04/line/1430746250002

> mp-h= could make more sense since you don't use it in your content

**Comment by elf-pavlik** [comment]
PROPOSAL: change `h=card` to `type=h-card`

It will allow use of types from outside of microformats vocabulary (e.g. ActivityStreams 2.0) and make it more aligned with [microformats type parsed out of HTML](http://microformats.org/wiki/microformats2-parsing#parse_an_element_for_class_microformats) 

``` json
{
  "items": [{ 
    "type": ["h-card"],
    "properties": {
      "name": ["Ben Ward"],
      "url": ["http://benward.me"]
    }
  }]
}
```

**Comment by dissolve** [comment]
I always thought h= seemed rather random. Especially considering u-url is url= not u=.
It is slightly different since it is the the type of the main object. 

I use mp-type= currently to specify type of h-entry (checkin, note, etc). This would conflict with that for me.

**Comment by aaronpk** [comment]
In my very first draft I actually did use "u=" for the URL, but I was talked out of using single-letter properties quickly, since it quickly becomes unreadable once there are more than like two.

**Comment by elf-pavlik** [comment]
Looking at http://indiewebcamp.com/micropub#JSON_Syntax

`type` qualifies as data property and not so much mp-\* (API specific)

BTW in context of Social WG I really doubt that people will support adopting Microformats JSON instead of JSON-LD. I'll take a look at providing examples equivalent to ones in current micropub draft, but using JSON-LD. I guess we better discuss that particular issue in https://github.com/w3c-social/Social-APIs-Brainstorming so I'll put it there and link from here...

**Comment by aaronpk** [comment]
The form-encoded request uses `h=entry`, and is pretty widely implemented right now, so changing that to `type=h-entry` is essentially bikeshedding since no implementations have had trouble in practice with the current behavior.

When creating objects via a JSON post, the JSON Microformats object is sent, which includes a `"type":"h-entry"` value. (See http://micropub.net/draft/#json-syntax)

The suggestion of using `url` is accepted and has been incorporated.

If any of the other topics brought up in this thread are still relevant, please file new specific issues.
