### ISSUE TITLE
Add explanation/intro/scenario

### ISSUE THREAD

**Issue by dret** [w3c/Micropub#21]
when trying to come up with a good short description for addressing #19, it occurred to me that the current draft does not have a good explanation/intro/scenario section. it is probably easy for people with an indieweb background to understand micropub and its context and goals. but it may be useful to add some explanation when and how and why to use micropub for somebody reading this as a standalone spec.

**Comment by aaronpk** [comment]
@dret I added some additional background text. Do you think this is sufficient? Thanks for the suggestion!

**Comment by dret** [comment]
definitely an improvement, thanks!
i think i was mostly looking for a brief intro on what the spec actually defines. is it a media type? a protocol? a new way of combining existing media types into a new protocol? afaict, no media type is defined, but an HTTP-based protocol for how existing media types can be used for a specific publishing scenario. for me, having this "what's actually being defined" part always is very helpful, but then again, maybe i am not a good reference and that's too much technology focus.
