### ISSUE TITLE
Should `q=source` always return the URL of the post?

### ISSUE THREAD

**Issue by aaronpk** [w3c/Micropub#23]
The micro-panel client assumes that the `q=source` response will include the URL, which it then uses to update the post. However the URL had to be passed to the endpoint when querying for the source, so it's not strictly necessary to be in the response. Should clients assume they should use the same URL they queried when making the update? Or should they assume the URL will always be in the response?

cc @myfreeweb

**Comment by valpackett** [comment]
Hmm, I could add the url fallback, I just didn't think of it.

I guess passing the URL back is in the stateless spirit of HTTP/REST though :D

**Comment by aaronpk** [comment]
Let's not make this a requirement of the server, and instead put the burden on the client to remember the URL it's editing.
