### ISSUE TITLE
Add explicit note about string vs array values

### ISSUE THREAD

**Issue by aaronpk** [w3c/Micropub#24]
In form-encoded requests, all values are given as strings, e.g. `content=hello`. In JSON format, all values MUST be given as arrays, e.g. `{"content":["hello"]}`. This needs to be made explicit in the spec, and all examples should be verified that they match this convention.

Does this sound reasonable? cc @myfreeweb

**Comment by valpackett** [comment]
The examples _are_ all arrays. Sure, making this explicit is great!

**Comment by aaronpk** [comment]
Added text clarifying that values must be arrays for JSON. There was already enough text for form-encoded.
