### ISSUE TITLE
Drop form-encoded support for updates?

### ISSUE THREAD

**Issue by aaronpk** [w3c/Micropub#25]
Right now, the data passed to the micropub endpoint for updates is the same structure for form-encoded and JSON requests, but both content types are allowed.

It sounds like the implementors so far are all in agreement that it wasn't a lot of extra work to support both form-encoded and JSON syntax for updates, but that it would be simpler to only have to support JSON.

This thread is to capture the discussion on whether the spec should allow a client to send both content types, or whether updates should require JSON requests.

If the spec allows clients to send either, then servers will be required to support both, in order to ensure interoperability.

**Comment by akuckartz** [comment]
:+1: for JSON(-LD)

**Comment by barryf** [comment]
I'm working through supporting updates (and deletes/undeletes) via JSON and without support for form-encoding so 👍.

**Comment by aaronpk** [comment]
Sounds good. This will also help better separate the classes of implementations of clients that only create posts vs clients that create and update posts.
