### ISSUE TITLE
Clear up language regarding file upload and media endpoint

### ISSUE THREAD

**Issue by richardcarls** [w3c/Micropub#29]
I agree with this:

> I think any micropub endpoint creating h-entrys should be able to accept media like photo/audio/video as _both_ a multipart-encoded file upload as well as a plain URL. I wouldn't want to require one or the other though. Aaron Parecki 11:52, 4 April 2015 (PDT) 

It allows a simple client, like an HTML form posting directly to an endpoint, to trivially support file uploads by posting multipart/form-data exclusively.

On the other hand, a micropub endpoint shouldn't _need_ to be responsible for receiving and processing (and storing) file uploads, when this is already covered by Media Endpoint.

If I'm reading the spec correctly, a micropub endpoint is now required to accept file uploads via multipart. As an aspiring implementer/contributor, this is kind of a turn-off. I would rather deal with uploads separately, or better yet, delegate to some kind of futuristic Media Endpoint service that handles it all for me.

**Comment by aaronpk** [comment]
@richardcarls Thanks for the note! I agree that a server shouldn't be required to accept file uploads if there is a media endpoint specified. What part of the spec indicated that the endpoint is required to accept file uploads? I am reviewing it and can't find a mention of that. I can make it more explicit that if there is a media endpoint specified, the micropub endpoint doesn't need to handle uploads though.

**Comment by richardcarls** [comment]
If a client queries a micropub server and discovers it's not configured with a media endpoint, does it then assume that the server will accept multipart as a fallback?

There are a couple sections on including files for certain properties; explicitly stating _"in the absence of a media endpoint, a client [**must** | **may**] include files with other properties in a multipart request"_ would help clear things up.

**Comment by aaronpk** [comment]
Yes, that's the behavior I would expect. I'll add some language to help clear it up. Thanks!

**Comment by aaronpk** [comment]
Thanks! This has been addressed in the latest draft. Specifically, http://micropub.net/draft/#uploading-files and http://micropub.net/draft/#conformance-classes If this addresses the issue to your satisfaction would you please close the issue? Thanks!

**Comment by richardcarls** [comment]
In addition to specifying multipart/form-data as required in the absence of a media endpoint, I think it would be good to conversely specify x-www-form-urlencoded as required _in conjunction_ with a media endpoint. Currently there's no server requirement stated for supporting good 'ole urlencoded on create.
