### ISSUE TITLE
references to normative/informative dependencies

### ISSUE THREAD

**Issue by elf-pavlik** [w3c/Micropub#3]
Examples
- http://www.w3.org/TR/activitystreams-core/#references

Tooling like http://www.specref.org/ can help with it (also built into Bikeshed and ReSpec)

For now I can think of at least referencing
- http://www.w3.org/TR/html5/forms.html#url-encoded-form-data
- https://tools.ietf.org/html/rfc5988#section-5.3 (https://github.com/converspace/webmention/issues/29)
- http://tools.ietf.org/html/rfc6750#section-2
- http://tools.ietf.org/html/rfc5870

**Comment by aaronpk** [comment]
Here are a few, I'm tracking some more down in the mean time https://indiewebcamp.com/wiki/index.php?title=Micropub&action=historysubmit&diff=19028&oldid=18958

**Comment by elf-pavlik** [comment]
Thanks! I linked to http://www.specref.org/ since I see having dedicated references section very useful to get quick overview of what spec builds upon, especially **normative** references. e.g. http://www.w3.org/TR/activitystreams-core/#references

**Comment by aaronpk** [comment]
I didn't understand what specref.org was for. I tried searching for some of the specs I was looking for by keyword but it never returned any results.

**Comment by aaronpk** [comment]
References have been added in the new respec version of the draft.
