### ISSUE TITLE
Rename "mp-action" to "action"

### ISSUE THREAD

**Issue by aaronpk** [w3c/Micropub#32]
Now that only JSON requests are supported for updates, we don't need to namespace the name of the parameter by prefixing `mp-` like we would with form-encoded requests. In JSON format, all the properties of the object being updated are specified in a nested object, so there is no ambiguity about whether an un-namespaced parameter would be part of the post.

e.g., change

``` json
{
  "mp-action": "update",
  "url": "http://example.com/post/1",
  "replace": {
    "content": ["hello moon"]
  }
}
```

to 

``` json
{
  "action": "update",
  "url": "http://example.com/post/1",
  "replace": {
    "content": ["hello moon"]
  }
}
```

I would appreciate feedback from anyone who has implemented updates for a micropub client or server. cc @barryf @myfreeweb

**Comment by bear** [comment]
That matches the internal view of a micropub event for my framework so I'm +1 to that change

**Comment by voxpelli** [comment]
I can make that work with my micropub endpoint so I'm +1 as well

**Comment by barryf** [comment]
👍 Makes sense. I'm still working on my client and it was no effort to change.

**Comment by aaronpk** [comment]
Thanks! This has been done in the latest draft.
