### ISSUE TITLE
Specify what a mp-* instruction is and how to add new ones

### ISSUE THREAD

**Issue by voxpelli** [w3c/Micropub#33]
It is my understanding that all `mp-*` properties are instructions for the Micropub endpoint, but this isn't explicitly stated anywhere.

Rather, in `3.2` it states:

> `mp-*` - reserved for future use

But doesn't specify for who's future use.

In `4.1` we can find a comment after `mp-syndicate-to`:

> This property is giving a command to the Micropub endpoint, rather than just creating data, so it uses the mp- prefix.

But this is the only place that mentions that and it's just a comment.

There's also no mentions of where `mp-syndicate-to` itself is specified or how one can add new ones and if there's any way to add experimental ones or vendor ones such as one can in [eg. microformats 2](http://microformats.org/wiki/microformats-2-faq#how_do_you_use_experimental_microformats_and_property_names) or whether there is a registry of some kind [like for link relations](http://microformats.org/wiki/rel-registry).

I think new instructions/commands to the Micropub servers itself will become useful in the future so defining how one would go about adding such a one and what their purpose is would be great 👍

**Comment by aaronpk** [comment]
Thanks, I've added some text clarifying this. Let me know if you think this is clearer! http://micropub.net/draft/#reserved-properties

**Comment by voxpelli** [comment]
Better!

I still think a pointer on how to create a non-experimental `mp-` instruction would be good. If one should add it to a registry, use a specific naming scheme or some other mechanism to avoid naming collisions. Especially as it says "reserved for future use" – unless we specify a way to become that "future use", then it will just be reserved and no-one will really be able to add a non-experimental one without updating the Micropub spec itself?

As an example of the above it would probably be good to have `mp-syndicate-to` be specified/defined in a way similar to what one can expect other new non-experimental instructions be.

**Comment by voxpelli** [comment]
Syncing up the specification on how to add new `mp-` instructions with how to add new query-formats would probably be a good idea as well – they both share the same challenges in regards to possible naming collisions and should be treated as equally "reserved for future use".

Either it should be stated that everyone could add everything there as they go along and just use common sense to avoid collisions.

Previously on IRC https://tools.ietf.org/html/rfc6648 has been brought up in regards to this – it has some good ideas in it in this regard that could help in figuring this out.

**Comment by aaronpk** [comment]
@voxpelli How about explicitly stating that the IndieWeb wiki should be used to incubate (document and develop) extensions, both for `mp-*` instructions as well as `q=*` queries. That way at least people will have a place to go to find out what else people are working on. Maybe a page like https://indieweb.org/Micropub-extensions?

**Comment by voxpelli** [comment]
@aaronpk Sounds like a good enough solution

**Comment by aaronpk** [comment]
Thanks! Just pushed that update.
