### ISSUE TITLE
Accessibility Review

### ISSUE THREAD

**Issue by aaronpk** [w3c/Micropub#34]
https://lists.w3.org/Archives/Public/public-apa/2016Jul/0012.html

```
This is a draft comment for the publishers of Micropub from APA.  Please
make your comments on this thread.

APA Recommendations for Micropub
Micropub would benefit from an Accessibility section. The section should
define a best practice (SHOULD) method of uploading and downloading
images/media and associated accessibility related items. Examples of
accessibility related items for an image are alternative text appropriate
for use with an img element alt property and an image description. Examples
of accessibility related items for media are closed caption tracks and a
document (transcript).

Micorpub should include examples for uploading and downloading an image and
media with accessibility related items that follow the best practice.


     Regards,                                                 

    Fred Esch                                                 
 Watson, IBM, W3C                                             
  Accessibility                                               

 IBM Watson       Watson Release Management and Quality       
```

**Comment by aaronpk** [comment]
https://lists.w3.org/Archives/Public/public-apa/2016Jul/0013.html

```
Hi, Fred:

I have one quick edit relating to image descriptions. I would add the
parenthetical ", where needed," as not all images require a long
description.

Janina
```

**Comment by aaronpk** [comment]
In order to provide a mechanism for supplying image alt text, there needs to be a corresponding parsed result of the alt text in the microformats2 JSON. I've opened an issue there: https://github.com/microformats/microformats2-parsing/issues/2

**Comment by dissolve** [comment]
To document, it looks like twitter uses an metadata creation seperate from the media endpoint.  Thus the alt-text is tied directly to the image
https://dev.twitter.com/rest/reference/post/media/metadata/create

**Comment by kevinmarks** [comment]
By posting html in the content, all accessibility markup can be preserved. If you link to an externally hosted photo by URL this works too.

If you use a media endpoint to upload a photo, then link to that URL in the content, that enables alt and other markup implicitly. 

It's not clear in http://micropub.net/draft/#uploading-files if the url given in the multipart section for the uploaded photo can be referred to in the content posted at the same time.

We could amend the media endpoint model to accept other metadata like alt, longdesc etc about the image, but that seems to create more complexity for both clients and servers.

**Comment by aaronpk** [comment]
> It's not clear in http://micropub.net/draft/#uploading-files if the url given in the multipart section for the uploaded photo can be referred to in the content posted at the same time.

Can you break that out into a new issue? That's worth discussing more.

**Comment by aaronpk** [comment]
For reference, that issue is now broken out here: https://github.com/w3c/Micropub/issues/35

**Comment by aaronpk** [comment]
There is currently some brainstorming going on about this issue with the Microformats spec. The current consensus would result in the following Micropub request to create a post with alt text on the photo:

```
h=entry&
name=Hello+World&
photo[value]=http://example.com/globe.gif&
photo[alt]=spinning+globe+animation
```

This could then be rendered as the following HTML:

``` html
<div class="h-entry">
  <p class="p-name">Hello World</p>
  <img class="u-photo" src="globe.gif" alt="spinning globe animation">
</div>
```

**Comment by aaronpk** [comment]
I've added some text describing how to include alt text based on the assumption that the current Microformats 2 proposal will be incorporated into the parsing spec. I have also added a note indicating such, and that if the Microformats 2 issue is resolved differently, we should update the Micropub spec accordingly.

http://micropub.net/draft/#uploading-a-photo-with-alt-text

**Comment by aaronpk** [comment]
We now have a test tool that supports sending a request that includes image alt text, and four of the five implementation reports indicate their server supports this feature.

https://micropub.rocks/reports

**Comment by michael-n-cooper** [comment]
Thanks for this stuff. The APA WG has determined that its requests have been met.

https://www.w3.org/WAI/APA/wiki/Micropub
