### ISSUE TITLE
no way to indicate direction or language of name

### ISSUE THREAD

**Issue by r12a** [w3c/Micropub#37]
[comment by Addison Phillips]

https://www.w3.org/TR/micropub/#configuration

In the examples above, natural language data is shown for the 'name' property, but there is no way to indicate language or direction.

**Comment by aaronpk** [comment]
I just tested this with Hebrew (right-to-left), and it looks like it round-trips properly when everything is utf8. 

Below is an example of HTML that contains RTL characters, and the parsed Microformats result in JSON form.

``` html
<div class="h-entry">
  <h1 class="p-name">שלום עול</h1>
</div>
```

``` json
    {
      "type": [
        "h-entry"
      ],
      "properties": {
        "name": [
          "\u05e9\u05dc\u05d5\u05dd \u05e2\u05d5\u05dc\u05dd"
        ]
      }
    }
```

Taking the string in that JSON and outputting it in HTML results in the characters displaying in the proper RTL order.

I also tested this with my Micropub client and server implementation and it worked fine. Here are the resulting buttons in my posting interface:

![syndication buttons](https://aaronparecki.com/media/file-20160724214738-82162.png)

Is there some other reason for needing a way to indicate the direction of the text? It looks like the utf8 encoding handles it.

As far as language, the client can use the HTTP `Accept-Lang` header to request a localized version of the values if applicable. Would it suffice to include this header in the example?

**Comment by r12a** [comment]
@aaronpk it is very much to be expected that a string such as the one you tested would work, since it contains no punctuation or bidirectional text. Phrases that do contain punctuation or bidi text need to have the correct base direction set for success. For example, in the phrase "פעילות הבינאום, W3C" the W3C should appear to the left of the Hebrew text. It can only do so if the base direction (ie. the general directional context) for the phrase is somehow set to RTL.  (For more detail see https://www.w3.org/International/articles/inline-bidi-markup/).  Here's another example for which the same applies: "The title is مفتاح معايير الويب! in Arabic."  In this case, the exclamation mark should appear to the left of the Arabic text.

Btw, i'm wondering why the Hebrew text is escaped in the parsed JSON form you show above?

**Comment by r12a** [comment]
> (For more detail see https://www.w3.org/International/articles/inline-bidi-markup/). Here's another example for which the same applies: "The title is مفتاح معايير الويب! in Arabic." In this case, the exclamation mark should appear to the left of the Arabic text.

Since we've needed to explain this a number of times recently, i added some text to the article [Unicode Bidirectional Algorithm basics](http://w3c.github.io/i18n-drafts/articles/inline-bidi-markup/uba-basics.en) that explains this a little more gently than the article i just referred to (see esp. the section [Beyond the bidi algorithm](http://w3c.github.io/i18n-drafts/articles/inline-bidi-markup/uba-basics.en#beyond)). (These links are to the editor's version while we review it prior to uploading to the stable URL.)

**Comment by aaronpk** [comment]
Thanks, that's a really helpful article.

Doesn't the [RTL mark character](https://en.wikipedia.org/wiki/Right-to-left_mark) solve this problem though? That would allow the neutral punctuation character to be grouped with the RTL characters.

**Comment by aaronpk** [comment]
The ActivityStreams spec actually has an example and some wording that could be used. From http://w3c.github.io/activitystreams/core/index.html#naturalLanguageValues

> Because the name (and corresponding `nameMap`) property does not permit HTML markup, the Unicode Bidirectional Control characters [BIDI] may be used to identify text direction:

```
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Object",
  "nameMap": {
    "en": "\u202Bפעילות הבינאום, W3C\u202C"
  }
}
```

It appears that utf-8 can solve this then?

**Comment by r12a** [comment]
I see that the spec has been moved to CR.  What was the resolution for this discussion?

**Comment by aaronpk** [comment]
We moved the spec to CR with a note about this outstanding issue, with the intent to publish a revised CR in the near future. 

Now that ActivityStreams has resolved their similar issue, could we adopt the recommendation they included? https://github.com/w3c/activitystreams/commit/b94e68deba7768bd1c166b38fd0f3e4aff4943e8#diff-907da620c77a22aa53b08f7575d5d7f3R1463

We would include text that recommends using the Unicode Bidirectional Control characters and reference `[[BIDI]]`, and include an example of right-to-left text.

**Comment by r12a** [comment]
I'm certainly hoping we have indeed found a workable resolution for the AS issue. I think we still need to just cross the Ts and dot the Is, see my comments at https://github.com/w3c/activitystreams/issues/336#issuecomment-240097693 (mostly editorial, but there are a couple of areas i just want to ensure that we have joint clarity on, and make sure that there are no further objections from the i18n folks).

I'll ask Addison to get back to you with an answer, hopefully soon.  Do you need a reply urgently?

**Comment by r12a** [comment]
@aaronpk do you have a link to the note you mentioned?  I can't seem to find it.

**Comment by aaronpk** [comment]
@r12a sorry, I actually had mis-remembered that, the note I was thinking of was actually about the accessibility issue.

In today's call, the group resolved to adopt the same language used by AS2 for specifying the base direction https://www.w3.org/wiki/Socialwg/2016-09-06-minutes#Summary_of_Resolutions

I've gone ahead and added that to the latest editor's draft. Would you take a look and let me know if this is sufficient? http://micropub.net/draft/#bidirectional-text

**Comment by r12a** [comment]
@aaronpk i suspect that, by shortening the part about consumers, we lost something important.

For html content, consumers can't use simple first strong directional character checks to identify the base direction, since the markup will always cause it to fail to identify a RTL base direction.  Furthermore, directional information may be already encoded in the html markup, and that would trump any control character. 

That's why the AS version carries the text "SHOULD identify the base direction of any given natural language value by either scanning the text for the first strong directional character not contained within a markup element; or by utilizing directional markup where provided".

The AS text also mentions that the consumer needs to build directional information around the JSON string in the target destination, because the controls used are only markers – they don't produce the right directional behaviour automatically in the destination.

So i guess i'm suggesting to make the text more like the AS original.

(Btw, i assume that you have been following the AS discussions and that you're aware of http://w3c.github.io/i18n-discuss/notes/json-bidi, which tries to take a longer view on all this.)

**Comment by akuckartz** [comment]
@r12a The URL you provided regarding "json-bidi" contains a "localhost" domain.

**Comment by r12a** [comment]
thanks, @akuckartz . i fixed the link.

**Comment by aaronpk** [comment]
@r12a I've pushed an update to the text, would you please review? I tried to keep it more similar to the AS2 text.

http://micropub.net/draft/#bidirectional-text

**Comment by r12a** [comment]
still a small change needed, i think:

> identify the base direction of any given natural language value by either: for plaintext values, scanning the text for the first strong directional character; or for HTML values, by utilizing directional markup.

probably needs to say something like:

"identify the base direction of any given natural language value by either: for plaintext values, scanning the text for the first strong directional character; or for HTML values, by utilizing directional markup**, if available, or otherwise scanning for the first strong directional character not contained in a markup tag**."

that would explain how to do it when the markup doesn't contain directional information.

make sense?

**Comment by aaronpk** [comment]
@r12a yes that makes sense, thanks! I've incorporated the updated text.

I'm closing this issue as I assume this was the only change needed, but feel free to let me know otherwise.
