### ISSUE TITLE
encoding health warning for x-www-urlencoded

### ISSUE THREAD

**Issue by r12a** [w3c/Micropub#39]
[by Addison Phillips]

https://www.w3.org/TR/micropub/#create

The spec says in part:

> Clients and servers MUST support creating posts using the x-www-form-urlencoded encoding, and MAY also support creating posts using the JSON syntax.

No mention is made of the fact that URL encoded should use the UTF-8 encoding.

**Comment by aaronpk** [comment]
I've added some explicit mentions of utf-8 encoding. Can you take a look at the changes here and let me know if that will suffice? https://github.com/w3c/Micropub/commit/82a49a3fa6ff6b19923344eae1288bf367f3b2bf

**Comment by aaronpk** [comment]
Confirmed in the f2f meeting that this is sufficient.
