### ISSUE TITLE
Add MAY/SHOULD/MUST to http://micropub.net/draft/#querying

### ISSUE THREAD

**Issue by cweiske** [w3c/Micropub#42]
It's not clearly stated if server MUST, SHOULD or MAY implement the #querying commands config, source and syndicate-to.

**Comment by voxpelli** [comment]
I would say `MAY` on implementing but `SHOULD NOT` on responding with anything else but the specified responses when a request is made to any of the specified queries (if that's not implied).

It would also be useful with some similar notes on what to consider when adding new queries outside of the ones specified in the standard as I was suggesting for `mp-*` properties in #33, to encourage additional query extensions outside of these three basic ones.

**Comment by aaronpk** [comment]
Thanks. I've added supporting text in 4b5f91b00566319a39957576bafbac0db59ab25d 

Please close this issue if you feel this addresses the issue!
