### ISSUE TITLE
Make 3.3.5 explanation more readable

### ISSUE THREAD

**Issue by cweiske** [w3c/Micropub#44]
http://micropub.net/draft/#response states:

> If the server is going to return 202, it MUST ensure the object will be created successfully prior to returning 202, as clients will expect the object at the indicated URL to exist at some point in the (near) future. In other words, the server must do any error checking and validation before returning 202.

The first sentence is not really clear in its meaning. The second sentence's meaning is much more clear.

**Comment by etiennewan** [comment]
What about :

> The server MUST ensure the object will be created successfully prior to returning 202, as clients will expect the object at the indicated URL to exist in the (near) future with this response.

That's only removing the first part of the sentence, to be honest.

**Comment by aaronpk** [comment]
I've rephrased that whole paragraph, let me know if this looks good: https://micropub.net/draft/#response

**Comment by etiennewan** [comment]
Looks good. Good point into saying the validation process MUST be synchronous before any asynchronous processing.
