### ISSUE TITLE
MicroPub normatively references IndieAuth, a non-stable standard

### ISSUE THREAD

**Issue by cwebber** [w3c/Micropub#47]
MicroPub currently references IndieAuth, which is currently a loose collection of documents on a wiki.  This does not fulfill the requirements for stable specifications required within the working group.

Presumably, this could either be dropped, or IndieAuth could go through changes to make it stable somehow in a way that meets group requirements.

**Comment by aaronpk** [comment]
Not sure where you got the idea that it's a normative reference. It's clearly listed as an informative reference in the list of references in the spec.

**Comment by cwebber** [comment]
There are two references to IndieAuth that say "SHOULD"?

If that still falls within the realm of informative, it's okay to close this, but I thought that was a normative reference.

**Comment by aaronpk** [comment]
One reference mentions IndieAuth but is actually talking about discovery, which is part of the Micropub spec.

The other talks about authorization, which normatively references OAuth 2.0.

**Comment by rhiaro** [comment]
The references are in normative sections and say SHOULD. They need to be explicitly called out as informative if they are. Just listing them under 'informative' doesn't make it so.

**Comment by rhiaro** [comment]
I figure the discovery reference doesn't need to reference IndieAuth so you can probably just drop it from that one.

In Authorization, it might help to make the wording around IndieAuth explicitly informative, rather than rolling it in with with the OAuth SHOULD.

**Comment by akuckartz** [comment]
Section 2.1.1 talks about a "conforming Micropub client" and refers to IndieAuth using a SHOULD keyword. And the title of section 2 is "Conformance". If that is not normative nothing is.

**Comment by aaronpk** [comment]
I'll remove "given an [IndieAuth] identity URL" from conformance since that won't change the meaning.

@rhiaro Do you have a suggestion for new wording for the Authorization section?

**Comment by rhiaro** [comment]
How about:

> An app that wants to post to a user's Micropub endpoint will need to obtain authorization from the user in order to get an access token. Authorization SHOULD be handled via the OAuth 2.0 [RFC6749] protocol. Applications MAY use the [IndieAuth] extension to OAuth 2.0 which supports endpoint discovery from a URL. See Obtaining an Access Token for more details.

**Comment by cwebber** [comment]
LGTM.  I'd say, write that in!

**Comment by aaronpk** [comment]
I've added the updated text to the latest editor's draft: http://micropub.net/draft/#authorization

Look good?

**Comment by cwebber** [comment]
Looks good!
