### ISSUE TITLE
Clarify if updates container "either" or "at least one of" replace/add/delete

### ISSUE THREAD

**Issue by cweiske** [w3c/Micropub#51]
A sentence in the "update" section isn't that clear:

> 3.4 Update
> ...
> The request MUST also include _either_ a replace, add or delete property containing the updates to make.

"either" would suggest that only one of them may be specified in a request.

https://github.com/w3c/Micropub/issues/14#issuecomment-151163129 on the other hand suggests that all of them may be in a single request:

> The idea of the single "edit" is based on the idea of an "edit post", which is similar to a Github pull request. A pull request contains many changes, including replacing, adding and deleting content.

**Comment by tantek** [comment]
Looks like multiple edits to properties/values in a single post were resolved to be allowed/required by implementations to support: https://github.com/w3c/Micropub/issues/22

**Comment by aaronpk** [comment]
Thanks. I've updated the text to be more clear.
