### ISSUE TITLE
Why SHOULD store unrecognized properties?

### ISSUE THREAD

**Issue by dissolve** [w3c/Micropub#57]
The unrecognised properties sections says that clients SHOULD store any unrecognised properties.

> This allows clients to post rich types of content to servers that recognize it, while also posting fallback content to servers that don't.

This argument does not seem to support strongly recommending storage of unrecognised properties.

The only reasoning I can see is that a server does not YET understand some value and it can later go back and reprocess this.  But that is basically outside the domain of the API and is dictating back-end implementation.

**Comment by aaronpk** [comment]
You're right, specifying that a server should store the property doesn't really help with interop. The explanation in the spec that you quoted does not need that behavior. I updated the text to say that servers MUST ignore unrecognized properties, which does help interop by not having some servers reject requests from clients that other servers support.

https://micropub.net/draft/#unrecognized-properties

**Comment by dissolve** [comment]
:+1:
