### ISSUE TITLE
requirements for query options.

### ISSUE THREAD

**Issue by dissolve** [w3c/Micropub#58]
I only see that servers SHOULD support configuration query, but I'm unsure which values are required.

I'm assuming MAY for q=media-endpoint since it might not have a media-endpoint (this is also not really mentioned as a query value in the configuration query section.)

The largest confusion for me is if I MUST support returning source content or not.

**Comment by aaronpk** [comment]
In the [conformance section](https://micropub.net/draft/#servers), it says:

> Servers that support updating posts must support the source content query
> 
> Servers that specify a Media Endpoint must support the configuration query, other servers should support the configuration query

Also at the bottom of the source content section it says:

> Servers that support updating posts must support the source content query.

Are those not clear, or did you miss them and maybe I should make them more obvious?

**Comment by dissolve** [comment]
Okay, I missed those.  The single sentence after examples is easy to miss in https://micropub.net/draft/#source-content
Perhaps moving that to the top would help.

**Comment by dissolve** [comment]
For some reason I thought there was a query for q=media-endpoint as well, but i see that it is just querying q=config.

Is there a reason to have q=syndicate-to and not just lump it under q=config as well?

**Comment by dissolve** [comment]
:+1:
 perhaps I should move the other question to a separate issue.

**Comment by aaronpk** [comment]
Alright, I moved it up higher, it was definitely kind of hidden at the bottom of those examples.

Sure, I was half way through a reply but I can reply there.

**Comment by dissolve** [comment]
created #59 

closing this issue
