### ISSUE TITLE
q=syndicate-to not needed?

### ISSUE THREAD

**Issue by dissolve** [w3c/Micropub#59]
Is there a reason to have q=syndicate-to and not just lump it under q=config as well?

If supporting q=syndicate-to should we also support q=media-endpoint as well as any other options that a server may add in the future?

**Comment by aaronpk** [comment]
The only reason `q=syndicate-to` is there and not lumped under `q=config` is that originally we started with only `q=syndicate-to`. However if we ever start adding more things to `q=config` then it's possible a client might want to get only the syndication endpoints without the rest of the payload, but that's kind of a future theoretical argument. (Quill does have a "reload syndication endpoints" button where it doesn't need anything except the syndication response).

**Comment by dissolve** [comment]
its not so theoretical in my case as I actually have several other options I use it for.
specifically I return an actions object which is what URLs to use for various actions 

https://indieweb.org/mp-config

i am also working on being able to store client specific configs in to this as well, so every time you log back in, you can fetch stored custom configurations.

**Comment by dissolve** [comment]
Thinking about it more, I think I am OK leaving the text as is.  Any added options would be way of extensions added later and they can always define new q= queries at that time.

**Comment by aaronpk** [comment]
Okay, sounds good.
