### ISSUE TITLE
add section with all the assumptions made

### ISSUE THREAD

**Issue by elf-pavlik** [w3c/Micropub#6]
It looks that micropub makes some assumption about how person will use it. Having them clearly listed, can help with understanding its design and prevent surprise of trying to use it in not intended way.

e.g. https://github.com/aaronpk/Micropub/blob/master/user-stories/user-posts-a-file.md

Possibly assumes that person wants to make a post about this photo to one's own feed. Also binary content (non structured data) seems to always use it's ~meta description to identify it.
- https://www.w3.org/wiki/Socialwg/MediaObject
- https://github.com/linkeddata/SoLiD#handling-metadata-for-non-rdf-resources

**Comment by elf-pavlik** [comment]
It also looks that micropub assumes that it needs to know how to render / present the data, while other servers can delegate rendering / presentation to clients. While also providing default ones who can change over time.

**Comment by elf-pavlik** [comment]
Does micropub spec makes assumption that person would only ever use a single micropub endpoint? http://indiewebcamp.com/micropub#Endpoint_Discovery

If I want to keep my images, calendars, address books etc. on different domains (accounts) while still using same identity to authenticate, it looks like currently i can't specify multiple micropub endpoints.

**Comment by aaronpk** [comment]
The introduction now clearly explains the intended use of the protocol.

Currently, all implementations assume a single Micropub endpoint for each identity. I could envision wanting to choose different backend endpoints for different purposes, but that would end up being more of a change to how IndieAuth works, and I would still want the default to be the way it currently works where the domain can point to a single Micropub endpoint.
