### ISSUE TITLE
Add a way to provide end user error messages

### ISSUE THREAD

**Issue by voxpelli** [w3c/Micropub#61]
In https://micropub.net/draft/#error-response it is specifically defined that any error message should not be shown to the end user, which means that any validation error or similar that may be due to special constraints in the micropub server – eg. enforcing some specific format of a slug or something – can't be communicated to the end user. The end user will only see something like `Invalid Request` / `An unexpected error has occurred` – which isn't very user friendly.

Adding this as a follow up to #49 as with this mechanism any such "errors" that's out of scope of Micropub could at least be handled in a graceful way through Micropub. Sorry for the late response.

**Comment by aaronpk** [comment]
This is a good idea, but it's too late in this process to add a feature as big as this. I agree with the need for it, but it's unfortunately not trivial to add, especially as there has been no experimentation with this in any current implementations as of yet.

The best thing to do would be to have implementations experiment with ways to solve this, and collect information and feedback on the [Brainstorming](https://indieweb.org/Micropub-brainstorming) page on the IndieWeb wiki.

**Comment by voxpelli** [comment]
I totally understand, I'll leave this open until I've had time to move it there, but you can mark it as non-blocking for the spec itself

**Comment by aaronpk** [comment]
I've copied this issue onto the Micropub-brainstorming page, where we can continue to iterate on it there.

https://indieweb.org/Micropub-brainstorming#Provide_end-user_error_messages
