### ISSUE TITLE
Note about access_token should be normative

### ISSUE THREAD

**Issue by rhiaro** [w3c/Micropub#62]
In https://micropub.net/draft/#reserved-properties it says "MUST NOT store `access_token`" but that's in a Note which (I think) makes it non-normative. Sounds like it should be normative, maybe move it out of the Note? (or if it's not normative, drop the MUST)

**Comment by aaronpk** [comment]
It's meant to be normative, and I put it in the "note" thingy to emphasize it. Happy to move it out of that if putting it in the "note" block implies it's non-normative.
