### ISSUE TITLE
Clarify the difference between points 3 & 6 of 2.1.3.

### ISSUE THREAD

**Issue by Zegnat** [w3c/Micropub#65]
What is the difference between the following two sentences, listed as [Conformance Classes for Servers](https://micropub.net/draft/#h-servers):

* “support creating posts using the `x-www-form-urlencoded` syntax” (point 3), and
* “support `x-www-form-urlencoded` requests for creating posts” (point 6).

Other than changing word order and swapping “syntax” for “requests”, these two sentences seem to convey exactly the same thing.

Was the second point meant to be about `multipart/form-data` instead? It would make sense to only require the implementation of `multipart/form-data` for servers that do not implement a separate Media Endpoint.

**Comment by aaronpk** [comment]
Wow you're absolutely right, I'm not sure how we didn't catch that earlier! I've updated the sentence to clarify it. Please close the issue if you're happy with the change! https://micropub.net/draft/#servers

**Comment by Zegnat** [comment]
This does fix the duplication.

Still have a question lingering. It now mentions “Servers that support creating posts with media”, does this mean there can be conforming Micropub servers that do not support creating posts with media? If so, that feels like a conflict with [3.3.1. Uploading Files](https://micropub.net/draft/#uploading-files) (emphasis mine):

> If there is no Media Endpoint, **the client can assume that the Micropub endpoint accepts files directly**, and can send the request to it directly

This is not a safe assumption if Micropub servers that only accept `x-www-form-urlencoded` for posts without media are conforming to the spec. That might be of little importance though.

(Side note: the sentence I quoted from 3.3.1. ends in a comma instead of a period.)

**Comment by aaronpk** [comment]
I see what you mean, but I don't think Micropub servers should be required to support media at all. It would be totally possible to have a text-only Micropub server that is still useful. I've attempted to add some language to clarify it:

> If the server supports posts with files, and there is no Media Endpoint, the client can assume...

Does that clear it up?

**Comment by Zegnat** [comment]
That takes care of my pedantry around file uploads 😉

Nice work @aaronpk. I’ll close this!
