### ISSUE TITLE
EDITORIAL: Mention prior art and supersedes MetaWeblog and AtomPub

### ISSUE THREAD

**Issue by tantek** [w3c/Micropub#67]
Just as Webmention now mentions Pingback as prior art (that is effectively superseded), Micropub should mention both MetaWeblog (see indieweb.org/MetaWeblog) and AtomPub (ibid) as prior art, and as explicitly superseded with specific noted advantages (simpler - no XML needed, more secure by default - use of OAuth instead of user/pass, etc.).

**Comment by akuckartz** [comment]
:+1:

**Comment by aaronpk** [comment]
Updated! https://micropub.net/draft/#background

**Comment by tantek** [comment]
Looks good! Thanks!
