### ISSUE TITLE
License

### ISSUE THREAD

**Issue by evanp** [w3c/Micropub#7]
If we choose it for the socialwg social API, will we be working to get this licensed under the W3C royalty-free license?

**Comment by aaronpk** [comment]
Is that different from the CC0 OWFa license?

**Comment by evanp** [comment]
Yes.

Evan Prodromou

**Comment by aaronpk** [comment]
I haven't read it, but I'm sure I wouldn't have a problem with it. Technically we'd need to get all other contributors to sign off on the re-licensing. Would there be any problem publishing it under the W3C license right now even if it does not end up being part of the socialwg deliverable?

**Comment by dissolve** [comment]
Assuming re-licensing is necessary for W3C, what do we need to get this started while the number of contributors is lower?  Forward this to @wseltzer?

**Comment by aaronpk** [comment]
This isn't a problem since all original contributions were CC0. Now that it's published on w3.org it has the W3C license.
