### ISSUE TITLE
3.4.3: Remove full properties and property values

### ISSUE THREAD

**Issue by cweiske** [w3c/Micropub#87]
https://micropub.net/draft/#h-remove only describes how to remove a full property and single values of properties.

How does a request look when both shall be achieved at the same time?

**Comment by aaronpk** [comment]
The syntax described does not support both types of actions in the same request.

**Comment by tantek** [comment]
Worth adding to an FAQ so we can close this? (no change to spec)

**Comment by aaronpk** [comment]
added a note to the spec to address this
