### ISSUE TITLE
Responses needs like example html

### ISSUE THREAD

**Issue by rhiaro** [w3c/Micropub#9]

**Comment by aaronpk** [comment]
@rhiaro, can you remind me what this issue was about?

**Comment by rhiaro** [comment]
Uhhhhh wow, this must have made _so_ much sense at the time that no elaboration was needed.

The only thing I can think is that it means an example for a `like-of` post with html content..? Which doesn't seem necessary or really make sense. Or an example of a http response with html content in? Also weird.

I guess just close this... if it's really important it'll come up again.

**Comment by aaronpk** [comment]
okay!
