### ISSUE TITLE
q – reserved property vs parameter?

### ISSUE THREAD

**Issue by sknebel** [w3c/Micropub#91]
Quoting from https://www.w3.org/TR/micropub/#reserved-properties:
> A few POST body property names are reserved when requests are sent as x-www-form-urlencoded or multipart/form-data.
> […]
> q - used to query a Micropub endpoint

but q= is only used during GET requests as a query-string parameter, and it's probably intended to reserve it for *this* use.

(https://www.w3.org/TR/micropub/#h-note2 already mentions that the endpoint URL can contain other parameters)

**Comment by aaronpk** [comment]
True, `q` isn't a reserved parameter for POST requests. GET requests don't need to list reserved parameters because the GET requests don't allow for arbitrary parameters anyway. I will just remove it from the list of reserved POST parameters.

**Comment by aaronpk** [comment]
This change is made here: https://micropub.net/draft/#reserved-properties

Please close the issue if you are satisfied, thanks!
