### ISSUE TITLE
5.3.5: Broken sentence

### ISSUE THREAD

**Issue by cweiske** [w3c/Micropub#94]
> The client looks for a `<link rel="micropub">` tag in the HTML head of the URL used to authenticate, or sends an HTTP Link header with a rel value of micropub.

"or sends an" is out of place here. Could be changed to "or if the server sends an".

**Comment by aaronpk** [comment]
Thanks, fixed in 5f8bdcf34f44c2f0c2227835ed132f510f66ad41
