### ISSUE TITLE
5.4 Scope: Link to OAuth 2.0 scope section

### ISSUE THREAD

**Issue by cweiske** [w3c/Micropub#96]
> The client may request one or more scopes during the authorization request. It does this according to standard OAuth 2.0 techniques, by passing a space-separated list of scope names in the authorization request. [RFC6749]

Should link to https://tools.ietf.org/html/rfc6749#section-3.3 directly.

**Comment by aaronpk** [comment]
Thanks, I added the direct link in the sentence: fe0a0e16a25e16106f8e4b2c72972bc4bff6264e Please close if you are satisfied!
