### ISSUE TITLE
Update doesn't specify the HTTP methods to be used.

### ISSUE THREAD

**Issue by karlcow** [w3c/Micropub#97]
In section https://www.w3.org/TR/micropub/#update which specifies how to update a post, nothing is mentioned about the HTTP Method required. I would expect a PUT or a POST if side effects.

**Comment by aaronpk** [comment]
This sentence is meant to indicate that you use a POST request:

> Updating entries is done with a JSON post describing the changes to make.

It should have probably used capital letters for "POST".

**Comment by karlcow** [comment]
Yup it currently says:

> Micropub servers SHOULD support updating **posts**, including adding and removing individual properties as described in this section.
> 
> Updating entries is done with a JSON **post** describing the changes to make.

What about:


> Micropub servers SHOULD support updating entries, including adding and removing individual properties as described in this section.
> 
> Updating entries is done by sending an HTTP POST with a JSON payload describing the changes to make.
